---
- import_tasks: apt-stuff.yml
- import_tasks: go-tools.yml
- import_tasks: python-tools.yml
- import_tasks: github-repos.yml
- import_tasks: gem-tools.yml
- import_tasks: npm-tools.yml
- import_tasks: snap-tools.yml
- import_tasks: wget-tools.yml
- import_tasks: curl-tools.yml
- import_tasks: vscode-extensions.yml
