---
- name: "Install pipx tools from git repositories"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'crackmapexec', url: 'git+https://github.com/Porchetta-Industries/CrackMapExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }

- name: "Install pipx tools from PyPI"
  community.general.pipx:
    name: "{{ item }}"
    state: latest
  loop:
    - kube-hunter
    - firefed
    - wafw00f
    - sslyze
    - droopescan
    - sqlmap
    - angr
    - volatility3
    - frida-dexdump
    - oletools
    - pwntools
    - pefile
    - z3-solver
    - malduck
    - uncompyle6
    - decompyle3
    - keystone-engine
    - stegoveritas
    - fickling
    - termcolor
    - cprint
    - pycryptodomex
    - requests
