---
- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install ngrok using snap
  community.general.snap:
    name: ngrok
    state: present

- name: Install GitHub CLI (gh) using snap
  community.general.snap:
    name: gh
    state: present

- name: Install PowerShell using snap
  community.general.snap:
    name: powershell
    state: present
