---
- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present

- name: Ensure snapd service is started
  service:
    name: snapd
    state: started

- name: Install ngrok using snap
  community.general.snap:
    name: ngrok
    state: present
  become: true
  become_method: sudo

- name: Install GitHub CLI (gh) using snap
  community.general.snap:
    name: gh
    state: present
  become: true
  become_method: sudo

- name: Install PowerShell using snap
  community.general.snap:
    name: powershell
    state: present
  become: true
  become_method: sudo
