---
- name: "Install VS Code extensions"
  shell: "code --install-extension {{ item }} --force"
  loop:
    - streetsidesoftware.code-spell-checker
    - ms-python.python
    - DEVSENSE.phptools-vscode
    - snyk-security.snyk-vulnerability-scanner
    - GitHub.copilot
  ignore_errors: yes
  become: true
  become_user: "{{ ansible_facts['user_id'] }}"
  environment:
    HOME: "{{ ansible_facts['env']['HOME'] }}"
    DISPLAY: ""
